apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: employee-db
  name: employee-db
spec:
  containers:
    - image: mongo:4.2.2
      name: employee-db
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: employee-db-claim0
  restartPolicy: OnFailure
  volumes:
    - name: employee-db-claim0
      persistentVolumeClaim:
        claimName: employee-db-claim0
status: {}
