apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-cluster
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-cluster
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: DOCKER_INTERNAL://kafka-cluster:29092,DOCKER_EXTERNAL://127.0.0.1:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: t_employee_registration:1:1
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: DOCKER_INTERNAL
            - name: KAFKA_LISTENERS
              value: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.13-2.7.0
          name: kafka-cluster
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
