apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: login-service
  name: login-service
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        - name: SPRING_DATA_MONGODB_DATABASE
          value: Login
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://login-db:27018/
      image: loginservice:3.0
      name: login-service
      ports:
        - containerPort: 9001
      resources: {}
  restartPolicy: OnFailure
status: {}
