apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: registration-db
  name: registration-db
spec:
  containers:
    - args:
        - mongod
        - --port
        - "27019"
      image: registration-mongo:1.0
      name: registration-db
      ports:
        - containerPort: 27019
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: registration-db-claim0
  restartPolicy: OnFailure
  volumes:
    - name: registration-db-claim0
      persistentVolumeClaim:
        claimName: registration-db-claim0
status: {}
