apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-ui
  name: angular-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: angular-ui
    spec:
      containers:
        - image: docker.io/margaritamorozova/angular-ui:2.0
          name: angular-ui
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always
status: {}
