apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: employee-service
  name: employee-service
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        - name: SPRING_DATA_MONGODB_DATABASE
          value: Employee
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://employee-db:27017/
      image: employeeservice:3.0
      name: employee-service
      ports:
        - containerPort: 9003
      resources: {}
  restartPolicy: OnFailure
status: {}
