apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka-service
  name: eureka-service
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_FETCH-REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
          value: "false"
      image: discovery-service:1.0
      name: eureka-service
      ports:
        - containerPort: 8761
      resources: {}
  restartPolicy: OnFailure
status: {}
