apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: react-ui
  name: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: react-ui
    spec:
      containers:
        - image: docker.io/margaritamorozova/react-ui:1.0
          name: react-ui
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
      restartPolicy: Always
status: {}
