FROM mongo:4.2.2
LABEL description="EmployeesDB"
ENV MONGO_INITDB_ROOT_USERNAME admin
ENV MONGO_INITDB_ROOT_PASSWORD pa55w0rd
ENV MONGO_INITDB_DATABASE admin
EXPOSE 27017
#ADD mongo-init.js /docker-entrypoint-initdb.d/

